### ISSUE TITLE
Find a way how to NOT run spec-cleaner on maintenance updates

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/spec-cleaner#172]
While spec-cleaner is now quite reliable it still generates quite a diff when working on the maintenance branches where the changes should be kept as minimal as possible.

Thus we should figure out some way how to avoid running it there.

**Comment by sleep-walker** [comment]
IMHO this problem should be solved outside of spec-cleaner. Make spec-cleaner invocation optional based on either project configuration or more ugly - project name regexp.

**Comment by scarabeusiv** [comment]
It seems osc is indeed inheriting this from the project metadata.
The getProjectGlobalServices function queries OBS server and gets the list of services to be executed.

@lnussel @DimStar77 guys do you guys manage the list or whom should I poke to discuss this?

**Comment by lnussel** [comment]
which services are run is defined in _product/_service. looks like the command used by osc collects all services from all linked projects. I've tried to add format_spec_file with mode disabled to 42.3:Update for testing. Can you give it a try to see if disabling that way works?

**Comment by scarabeusiv** [comment]
@lnussel Seems on local checkout it was still run:
`
scarabeus@bugaboo: ~/build_service/home:scarabeus_iv:branches:openSUSE:Leap:42.3:Update/hello $ osc build

Run source service: /usr/lib/obs/service/format_spec_file --outdir /home/scarabeus/build_service/home:scarabeus_iv:branches:openSUSE:Leap:42.3:Update/hello/tmp4cA3uo.format_spec_file.service`

**Comment by lnussel** [comment]
ok, so I switched it to disabled in main project

**Comment by scarabeusiv** [comment]
This should be disabled on Leap 15+ and older are obsolete -> can be closed.
