### ISSUE TITLE
Use %make_build instead of make %{?_smp_mflags}

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/spec-cleaner#229]
%make_build is in RPM for 5 years and thus covered by SLE12+

**Comment by plusky** [comment]
`%make_build` still is not supported on _SLE-12_ or _Leap-42*_ so I guess we should postpone this change

**Comment by scarabeusiv** [comment]
Ok thanks.

**Comment by marxin** [comment]
How long should we postpone it?

**Comment by Conan-Kudo** [comment]
Don't postpone it anymore.
