### ISSUE TITLE
spec-cleaner moves BuildRequires: inside conditional away

### ISSUE THREAD

**Issue by mwilck** [rpm-software-management/spec-cleaner#257]
This [spec file](https://github.com/rpm-software-management/spec-cleaner/files/3556373/hplip.spec.txt) contains a section with BuildRequires: inside a conditional:

    BuildRequires:  update-desktop-files
    if 0%{?with_new_pycups}
    # All printer driver packages should have "BuildRequires: cups-rpm-helper"
    # for automatic generation of Provides: tags.
    BuildRequires:  cups-rpm-helper
    %endif

When I run spec-cleaner on it (or format_spec_file, FTM), it moves that section down below all Requires: and Obsoletes: 

I wonder if that's intended behavior?

**Comment by mwilck** [comment]
This is [the spec file after running spec-cleaner over it](https://github.com/rpm-software-management/spec-cleaner/files/3556395/hplip.spec.after-cleaning.txt).

**Comment by scarabeusiv** [comment]
This is an intended behaviour indeed, the conditions are all moved in one location in the spec. It allows for easier review of all available conditionals later on.

**Comment by scarabeusiv** [comment]
Basically detecting the conditions and the alphabetic sorting caused all sort of trouble with nested conditions so we had to do something that could be reliably reproducable, and this was least worst of all the posible solutions.
