### ISSUE TITLE
Does it do dos2unix cleaning?

### ISSUE THREAD

**Issue by guoyunhe** [rpm-software-management/spec-cleaner#260]
Original issue here https://github.com/openSUSE/osc/issues/647

I sometimes copied some build commands from GitHub or websites. The copied text may contains `\r` and some editors don't convert it (vim). When I run `osc build`, it will throw an error at `\r` position.

**Comment by scarabeusiv** [comment]
well technically spec-cleaner converts it because it reads all the content and then just adds its own endlines. But feel free to test it if I am not mistaken.

**Comment by guoyunhe** [comment]
My test shows different:

```
echo -e "\r" >> my-package.spec
spec-cleaner my-package.spec
vi my-package.spec
```

![image](https://user-images.githubusercontent.com/5836790/66042845-49baaf00-e526-11e9-9c73-2feabde7bb1c.png)

**Comment by guoyunhe** [comment]
Oops, forgot to add `-i` option. Then it works. The ending `\r` or `^M` has been removed.
