### ISSUE TITLE
Wrong cleaning of pytest

### ISSUE THREAD

**Issue by mcepl** [rpm-software-management/spec-cleaner#261]
When running ``spec-cleaner -i`` on python-html5lib.spec I got change from:
```rpm
%python_expand %python_exec %{_bindir}/py.test --tb=short
```
to
```rpm
%python_expand %pytest --tb=short
```
OK, so the original was wrong as well. Should ``spec-cleaner`` check for this error?

**Comment by scarabeusiv** [comment]
i dunno, if it is in more than one place then yes, but if it is just one place it is not spec-cleaner;s job to protect you.
Same would be `%python_expand %python_expand`
