### ISSUE TITLE
Update the SUSE copyright string

### ISSUE THREAD

**Issue by ismail** [rpm-software-management/spec-cleaner#264]
Correct copyright string for SUSE is ```SUSE Linux LLC``` which can be confirmed by  visiting https://www.suse.com/c/news/suse-secures-openchain-certification-meeting-the-new-industry-benchmark-for-a-simplified-open-source-experience/

**Comment by scarabeusiv** [comment]
The new SUSE Linux LLC is there.

**Comment by aplanas** [comment]
Note that is not "SUSE Linux LLC", but "SUSE LLC", Linux was dropped, so https://github.com/rpm-software-management/spec-cleaner/commit/6b760c09b432cd7795bce674309e8a9dd159dd8c is wrong.

**Comment by ismail** [comment]
> Note that is not "SUSE Linux LLC", but "SUSE LLC", Linux was dropped, so [6b760c0](https://github.com/rpm-software-management/spec-cleaner/commit/6b760c09b432cd7795bce674309e8a9dd159dd8c) is wrong.

Nice catch!

**Comment by Conan-Kudo** [comment]
The new header is out of compliance, as it lacks the residency information.

E.g., for Red Hat stuff I had to put `Red Hat, Inc., Raleigh, North Carolina, United States of America.`

What's the location for SUSE now?

**Comment by ismail** [comment]
> The new header is out of compliance, as it lacks the residency information.
> 
> E.g., for Red Hat stuff I had to put `Red Hat, Inc., Raleigh, North Carolina, United States of America.`
> 
> What's the location for SUSE now?

Address is the same but why is an address is needed?

**Comment by Conan-Kudo** [comment]
@ismail My understanding is that for legal reasons, a location is required for company entities to establish _which_ entity it is. And for individuals, an email address is required to be able to contact them.

**Comment by ismail** [comment]
> @ismail My understanding is that for legal reasons, a location is required for company entities to establish _which_ entity it is. And for individuals, an email address is required to be able to contact them.

Well, I don't think it's a requirement. See https://opensource.google/docs/copyright/ for example.

**Comment by Conan-Kudo** [comment]
@ismail Hey, it was the reason I was given when *I* had to put it into the spec files when I was starting to contribute to openSUSE years ago...
