### ISSUE TITLE
Wrong replacement BuildArch to ExclusiveArch

### ISSUE THREAD

**Issue by mimi1vx** [rpm-software-management/spec-cleaner#289]
```%ifarch %{ix86}
ExclusiveArch:  i586 i686
BuildArch:      i686
%{expand:%%global optflags %(echo "%{optflags}"|sed -e s/i586/i686/) -march=i686 -mtune=generic}
%endif
```

is transformed by spec-cleaner to:

```
%ifarch %{ix86}
ExclusiveArch:  i586 i686
ExclusiveArch:  i686
%{expand:%%global optflags %(echo "%{optflags}"|sed -e s/i586/i686/) -march=i686 -mtune=generic}
%endif
```

**Comment by kstreitova** [comment]
Actually, it's not wrong. The only allowed value of `BuildArch` is "noarch", so the spec-cleaner automatically transforms any `BuildArch` with no "noarch" to `ExclusiveArch` as this is probably what the writer wanted to do.

**Comment by kstreitova** [comment]
Talked to @mimi1vx and we decided that we can close this issue as invalid.
