### ISSUE TITLE
incorrect placement of curly brackets

### ISSUE THREAD

**Issue by arunpersaud** [rpm-software-management/spec-cleaner#299]
Hi

when running spec-cleaner (v1.2.1) over a package on the opensuse build sever I ran into two problems.
Here are the lines from the diff between the original and the cleaned spec-file:

-BuildRequires:  %{python_module jupyter_server >= 1.8 with %python-jupyter_server < 2}
+BuildRequires:  %{python_module jupyter_server >= 1.8 with %{python}-jupyter_server < 2}

-%python_libalternatives_reset_alternative jupyter-nbclassic
+%{python_libalternatives_reset_alternative} jupyter-nbclassic

both lead to build errors due to incorrect(?) placement of the curly brackets?

The spec file can be found here:
https://build.opensuse.org/package/view_file/devel:languages:python:jupyter/python-nbclassic/python-nbclassic.spec?expand=1

**Comment by kubat-david** [comment]
Is the placement of the curly brackets in the second example really incorrect?
```
 -%python_libalternatives_reset_alternative jupyter-nbclassic
+%{python_libalternatives_reset_alternative} jupyter-nbclassic
```

**Comment by kubat-david** [comment]
It is, as it leads to build failures.

https://build.opensuse.org/package/live_build_log/home:dkubat:branches:devel:languages:python:jupyter/python-nbclassic/openSUSE_Tumbleweed/x86_64

`%python_libalternatives_reset_alternative` should probably be added to data/excludes-bracketing.txt
